# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestione_tavoli.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 571, 511))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_segnaOccupato = QtWidgets.QPushButton(self.widget)
        self.pushButton_segnaOccupato.setObjectName("pushButton_segnaOccupato")
        self.gridLayout.addWidget(self.pushButton_segnaOccupato, 1, 0, 1, 1)
        self.pushButton_segnaLibero = QtWidgets.QPushButton(self.widget)
        self.pushButton_segnaLibero.setObjectName("pushButton_segnaLibero")
        self.gridLayout.addWidget(self.pushButton_segnaLibero, 1, 1, 1, 1)
        self.tableWidget_listaTavoli = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_listaTavoli.setObjectName("tableWidget_listaTavoli")
        self.tableWidget_listaTavoli.setColumnCount(4)
        self.tableWidget_listaTavoli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_listaTavoli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_listaTavoli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_listaTavoli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_listaTavoli.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget_listaTavoli, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_segnaOccupato.setText(_translate("MainWindow", "Segna Occupato"))
        self.pushButton_segnaLibero.setText(_translate("MainWindow", "Segna Libero"))
        item = self.tableWidget_listaTavoli.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TavoloID"))
        item = self.tableWidget_listaTavoli.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Numero posti"))
        item = self.tableWidget_listaTavoli.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Numero persone"))
        item = self.tableWidget_listaTavoli.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Stato"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
