# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestione_ordinazioni.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(955, 678)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabella_ordinazioni = QtWidgets.QTableWidget(self.centralwidget)
        self.tabella_ordinazioni.setObjectName("tabella_ordinazioni")
        self.tabella_ordinazioni.setColumnCount(6)
        self.tabella_ordinazioni.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_ordinazioni.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_ordinazioni.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_ordinazioni.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_ordinazioni.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_ordinazioni.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabella_ordinazioni.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.tabella_ordinazioni, 0, 0, 1, 2)
        self.pulsante_aggiorna_tabella = QtWidgets.QPushButton(self.centralwidget)
        self.pulsante_aggiorna_tabella.setObjectName("pulsante_aggiorna_tabella")
        self.gridLayout.addWidget(self.pulsante_aggiorna_tabella, 1, 0, 1, 1)
        self.pulsante_segna_arrivato = QtWidgets.QPushButton(self.centralwidget)
        self.pulsante_segna_arrivato.setObjectName("pulsante_segna_arrivato")
        self.gridLayout.addWidget(self.pulsante_segna_arrivato, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tabella_ordinazioni.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabella_ordinazioni.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tavolo"))
        item = self.tabella_ordinazioni.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tabella_ordinazioni.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.tabella_ordinazioni.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Prezzo"))
        item = self.tabella_ordinazioni.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Stato"))
        self.pulsante_aggiorna_tabella.setText(_translate("MainWindow", "Aggiorna Tabella"))
        self.pulsante_segna_arrivato.setText(_translate("MainWindow", "Segna come arrivato"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
