# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestione_pagamenti.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 0, 751, 541))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_pagato = QtWidgets.QPushButton(self.widget)
        self.pushButton_pagato.setObjectName("pushButton_pagato")
        self.gridLayout.addWidget(self.pushButton_pagato, 4, 2, 1, 1)
        self.lineEdit_filtro = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_filtro.setObjectName("lineEdit_filtro")
        self.gridLayout.addWidget(self.lineEdit_filtro, 0, 1, 1, 1)
        self.label_filtro = QtWidgets.QLabel(self.widget)
        self.label_filtro.setObjectName("label_filtro")
        self.gridLayout.addWidget(self.label_filtro, 0, 0, 1, 1)
        self.pushButton_filtra = QtWidgets.QPushButton(self.widget)
        self.pushButton_filtra.setObjectName("pushButton_filtra")
        self.gridLayout.addWidget(self.pushButton_filtra, 1, 1, 1, 1)
        self.tableWidget_pagamenti = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_pagamenti.setObjectName("tableWidget_pagamenti")
        self.tableWidget_pagamenti.setColumnCount(4)
        self.tableWidget_pagamenti.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pagamenti.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pagamenti.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pagamenti.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pagamenti.setHorizontalHeaderItem(3, item)
        self.gridLayout.addWidget(self.tableWidget_pagamenti, 3, 0, 1, 3)
        self.pushButton_reset = QtWidgets.QPushButton(self.widget)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_pagato.setText(_translate("MainWindow", "Pagato"))
        self.label_filtro.setText(_translate("MainWindow", "Inserisci TavoloID:"))
        self.pushButton_filtra.setText(_translate("MainWindow", "Filtra"))
        item = self.tableWidget_pagamenti.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TavoloID"))
        item = self.tableWidget_pagamenti.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NumPersone"))
        item = self.tableWidget_pagamenti.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prezzo"))
        item = self.tableWidget_pagamenti.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Stato"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
