# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gestione_pagamenti.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gestione_Pagamenti(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetTavoli = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetTavoli.setGeometry(QtCore.QRect(0, 0, 401, 192))
        self.tableWidgetTavoli.setObjectName("tableWidgetTavoli")
        self.tableWidgetTavoli.setColumnCount(4)
        self.tableWidgetTavoli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTavoli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTavoli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTavoli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetTavoli.setHorizontalHeaderItem(3, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 200, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 200, 47, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 200, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(320, 200, 47, 13))
        self.label_4.setObjectName("label_4")
        self.lineEditID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditID.setGeometry(QtCore.QRect(10, 220, 71, 16))
        self.lineEditID.setObjectName("lineEditID")
        self.lineEditPersone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPersone.setGeometry(QtCore.QRect(110, 220, 71, 16))
        self.lineEditPersone.setObjectName("lineEditPersone")
        self.lineEditPrezzo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPrezzo.setGeometry(QtCore.QRect(210, 220, 71, 16))
        self.lineEditPrezzo.setObjectName("lineEditPrezzo")
        self.lineEditStato = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditStato.setGeometry(QtCore.QRect(310, 220, 71, 16))
        self.lineEditStato.setObjectName("lineEditStato")
        self.pushButtonAggiungi = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAggiungi.setGeometry(QtCore.QRect(10, 280, 91, 23))
        self.pushButtonAggiungi.setObjectName("pushButtonAggiungi")
        self.pushButtonAggiorna = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAggiorna.setGeometry(QtCore.QRect(130, 280, 91, 23))
        self.pushButtonAggiorna.setObjectName("pushButtonAggiorna")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidgetTavoli.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID Tavolo"))
        item = self.tableWidgetTavoli.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Persone"))
        item = self.tableWidgetTavoli.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prezzo"))
        item = self.tableWidgetTavoli.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Stato"))
        self.label.setText(_translate("MainWindow", "ID Tavolo "))
        self.label_2.setText(_translate("MainWindow", "Persone"))
        self.label_3.setText(_translate("MainWindow", "Prezzo"))
        self.label_4.setText(_translate("MainWindow", "Stato"))
        self.pushButtonAggiungi.setText(_translate("MainWindow", "Aggiungi Tavolo"))
        self.pushButtonAggiorna.setText(_translate("MainWindow", "Aggiorna Stato"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Gestione_Pagamenti()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
