# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pub_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GestionePub(object):
    def setupUi(self, GestionePub):
        GestionePub.setObjectName("GestionePub")
        GestionePub.resize(1030, 689)
        self.centralwidget = QtWidgets.QWidget(GestionePub)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 20, 1021, 501))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_pagamenti = QtWidgets.QPushButton(self.widget)
        self.btn_pagamenti.setObjectName("btn_pagamenti")
        self.gridLayout.addWidget(self.btn_pagamenti, 2, 1, 1, 1)
        self.btn_ordinazioni = QtWidgets.QPushButton(self.widget)
        self.btn_ordinazioni.setObjectName("btn_ordinazioni")
        self.gridLayout.addWidget(self.btn_ordinazioni, 1, 0, 1, 1)
        self.btn_visualizza_prenotazioni = QtWidgets.QPushButton(self.widget)
        self.btn_visualizza_prenotazioni.setObjectName("btn_visualizza_prenotazioni")
        self.gridLayout.addWidget(self.btn_visualizza_prenotazioni, 1, 1, 1, 1)
        self.btn_richieste_clienti = QtWidgets.QPushButton(self.widget)
        self.btn_richieste_clienti.setObjectName("btn_richieste_clienti")
        self.gridLayout.addWidget(self.btn_richieste_clienti, 0, 1, 1, 1)
        self.btn_visualizza_tavoli = QtWidgets.QPushButton(self.widget)
        self.btn_visualizza_tavoli.setObjectName("btn_visualizza_tavoli")
        self.gridLayout.addWidget(self.btn_visualizza_tavoli, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, -10, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        GestionePub.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GestionePub)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 24))
        self.menubar.setObjectName("menubar")
        GestionePub.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GestionePub)
        self.statusbar.setObjectName("statusbar")
        GestionePub.setStatusBar(self.statusbar)

        self.retranslateUi(GestionePub)
        QtCore.QMetaObject.connectSlotsByName(GestionePub)

    def retranslateUi(self, GestionePub):
        _translate = QtCore.QCoreApplication.translate
        GestionePub.setWindowTitle(_translate("GestionePub", "MainWindow"))
        self.btn_pagamenti.setText(_translate("GestionePub", "Pagamenti"))
        self.btn_ordinazioni.setText(_translate("GestionePub", "Ordinazioni"))
        self.btn_visualizza_prenotazioni.setText(_translate("GestionePub", "Visualizza Prenotazioni"))
        self.btn_richieste_clienti.setText(_translate("GestionePub", "Richieste Clienti"))
        self.btn_visualizza_tavoli.setText(_translate("GestionePub", "Visualizza Tavoli"))
        self.label.setText(_translate("GestionePub", "Gestione Pub"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GestionePub = QtWidgets.QMainWindow()
    ui = Ui_GestionePub()
    ui.setupUi(GestionePub)
    GestionePub.show()
    sys.exit(app.exec_())
