# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pub_home_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pub_Home(object):
    def setupUi(self, Pub_Home):
        Pub_Home.setObjectName("Pub_Home")
        Pub_Home.resize(564, 361)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        Pub_Home.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Pub_Home)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.NameLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.horizontalLayout.addWidget(self.NameLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.DateLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.DateLabel.setFont(font)
        self.DateLabel.setObjectName("DateLabel")
        self.horizontalLayout.addWidget(self.DateLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.IDLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.IDLabel.setFont(font)
        self.IDLabel.setObjectName("IDLabel")
        self.horizontalLayout.addWidget(self.IDLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        # Pulsante per gestire ordini
        self.GestioneOrdiniButton = QtWidgets.QPushButton(self.centralwidget)
        self.GestioneOrdiniButton.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.GestioneOrdiniButton.setFont(font)
        self.GestioneOrdiniButton.setObjectName("GestioneOrdiniButton")
        self.gridLayout_2.addWidget(self.GestioneOrdiniButton, 0, 0, 1, 1)
        
        # Pulsante per gestire tavoli
        self.GestioneTavoliButton = QtWidgets.QPushButton(self.centralwidget)
        self.GestioneTavoliButton.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.GestioneTavoliButton.setFont(font)
        self.GestioneTavoliButton.setObjectName("GestioneTavoliButton")
        self.gridLayout_2.addWidget(self.GestioneTavoliButton, 0, 1, 1, 1)
        
        # Pulsante per gestire pagamenti
        self.GestionePagamentiButton = QtWidgets.QPushButton(self.centralwidget)
        self.GestionePagamentiButton.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.GestionePagamentiButton.setFont(font)
        self.GestionePagamentiButton.setObjectName("GestionePagamentiButton")
        self.gridLayout_2.addWidget(self.GestionePagamentiButton, 1, 0, 1, 1)
        
        # Pulsante per aggiungere nuove ordinazioni
        self.AggiungiOrdineButton = QtWidgets.QPushButton(self.centralwidget)
        self.AggiungiOrdineButton.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        self.AggiungiOrdineButton.setFont(font)
        self.AggiungiOrdineButton.setObjectName("AggiungiOrdineButton")
        self.gridLayout_2.addWidget(self.AggiungiOrdineButton, 1, 1, 1, 1)
        
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem3)
        Pub_Home.setCentralWidget(self.centralwidget)
        self.actionCIso = QtWidgets.QAction(Pub_Home)
        self.actionCIso.setObjectName("actionCIso")
        self.actionCiao = QtWidgets.QAction(Pub_Home)
        self.actionCiao.setObjectName("actionCiao")

        self.retranslateUi(Pub_Home)
        QtCore.QMetaObject.connectSlotsByName(Pub_Home)

    def retranslateUi(self, Pub_Home):
        _translate = QtCore.QCoreApplication.translate
        Pub_Home.setWindowTitle(_translate("Pub_Home", "Pub - Home"))
        self.label_6.setText(_translate("Pub_Home", "Benvenuto"))
        self.NameLabel.setText(_translate("Pub_Home", "Nome, Cognome"))
        self.DateLabel.setText(_translate("Pub_Home", "Mercoledì 29/11/2024 20:40"))
        self.label_7.setText(_translate("Pub_Home", "ID Tavolo"))
        self.IDLabel.setText(_translate("Pub_Home", "1"))
        self.GestioneOrdiniButton.setText(_translate("Pub_Home", "Gestisci Ordini"))
        self.GestioneTavoliButton.setText(_translate("Pub_Home", "Gestisci Tavoli"))
        self.GestionePagamentiButton.setText(_translate("Pub_Home", "Gestisci Pagamenti"))
        self.AggiungiOrdineButton.setText(_translate("Pub_Home", "Aggiungi Ordine"))
        self.actionCIso.setText(_translate("Pub_Home", "CIso"))
        self.actionCiao.setText(_translate("Pub_Home", "Ciao"))