# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cliente_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClienteHome(object):
    def setupUi(self, ClienteHome):
        ClienteHome.setObjectName("ClienteHome")
        ClienteHome.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ClienteHome)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(370, 0, 58, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(100, 80, 631, 381))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_prenota_entrata = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        self.pushButton_prenota_entrata.setFont(font)
        self.pushButton_prenota_entrata.setObjectName("pushButton_prenota_entrata")
        self.gridLayout.addWidget(self.pushButton_prenota_entrata, 3, 1, 1, 1)
        self.pushButton_invia_ordine = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        self.pushButton_invia_ordine.setFont(font)
        self.pushButton_invia_ordine.setObjectName("pushButton_invia_ordine")
        self.gridLayout.addWidget(self.pushButton_invia_ordine, 3, 0, 1, 1)
        self.pushButton_richiedi_menu = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        self.pushButton_richiedi_menu.setFont(font)
        self.pushButton_richiedi_menu.setObjectName("pushButton_richiedi_menu")
        self.gridLayout.addWidget(self.pushButton_richiedi_menu, 0, 0, 1, 1)
        ClienteHome.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ClienteHome)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        ClienteHome.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ClienteHome)
        self.statusbar.setObjectName("statusbar")
        ClienteHome.setStatusBar(self.statusbar)

        self.retranslateUi(ClienteHome)
        QtCore.QMetaObject.connectSlotsByName(ClienteHome)

    def retranslateUi(self, ClienteHome):
        _translate = QtCore.QCoreApplication.translate
        ClienteHome.setWindowTitle(_translate("ClienteHome", "MainWindow"))
        self.label.setText(_translate("ClienteHome", "Ciao! "))
        self.label_2.setText(_translate("ClienteHome", "Seleziona un opzione:"))
        self.pushButton_prenota_entrata.setText(_translate("ClienteHome", "Prenota Entrata"))
        self.pushButton_invia_ordine.setText(_translate("ClienteHome", "Invia Ordine"))
        self.pushButton_richiedi_menu.setText(_translate("ClienteHome", "Richiedi Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClienteHome = QtWidgets.QMainWindow()
    ui = Ui_ClienteHome()
    ui.setupUi(ClienteHome)
    ClienteHome.show()
    sys.exit(app.exec_())
